openapi: 3.0.1
info:
  title: Swagger Express Template service
  description: >-
    This is swagger for OpenAPI service
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: laotuan@telio.vn
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: "http://swagger.io"
servers:
  - url: http://localhost:3000
    description: Main local server
tags:
  - name: healthcheck
    description: healthcheck API

paths:
  /v1/health:
    get:
      tags:
        - healthcheck
      summary: Health Check
      description: /v1/health
      operationId: healthcheck
      responses:
        200:
          description: health check success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Service Up
  

components:
  securitySchemes:
    api_key:
      type: apiKey
      name: Authorization
      in: header
